FROM kartoza/postgis

ADD pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
ADD puppet/modules/openstreetmap/templates/imposm-mapping.py /srv/imposm-mapping.py

ADD fetch_osm.sh /srv/fetch_osm.sh

RUN apt-get update && apt-get install curl nano -y && \
apt-get install python-pip libpq-dev build-essential python-dev protobuf-compiler libprotobuf-dev libtokyocabinet-dev python-psycopg2 libgeos-c1 -y && \
pip install imposm
