version: '2'

services:
    tilemill:
        build: .
        links:
            - pg
        volumes:
            - ./data:/srv/tilemill/maps-tiles/data
            - ./maps-ox:/root/Documents/MapBox/project/mapsox
            - ./mapbox_assets:/srv/tilemill/mapbox
        ports:
            - "20009:20009"
            - "20008:20008"
            - "1100:22"
    pg:
        build:
            context: .
            dockerfile: Dockerfile_postgis
        ports: 
            - "5432:5432"
